/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../src/components/open-url-modal/open-url-modal-component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from 'ionic-angular/navigation/nav-params';
import * as import9 from 'ionic-angular/navigation/view-controller';
import * as import10 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import11 from '../../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from 'ionic-angular/components/navbar/navbar';
import * as import13 from '../../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from 'ionic-angular/components/button/button';
import * as import17 from '../../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import18 from '../../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import19 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import20 from '../../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import21 from 'ionic-angular/components/content/content';
import * as import22 from '../../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import23 from 'ionic-angular/config/config';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from 'ionic-angular/components/app/app';
import * as import26 from 'ionic-angular/navigation/nav-controller';
import * as import27 from 'ionic-angular/components/toolbar/toolbar';
import * as import28 from 'ionic-angular/platform/platform';
import * as import29 from 'ionic-angular/platform/dom-controller';
import * as import30 from 'ionic-angular/platform/keyboard';
import * as import31 from '@angular/core/src/zone/ng_zone';
import * as import32 from 'ionic-angular/components/tabs/tabs';
import * as import33 from 'ionic-angular/components/icon/icon';
import * as import34 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import35 from '@angular/core/src/security';
export class Wrapper_OpenUrlModalCmp {
  /*private*/ _eventHandler:Function;
  context:import0.OpenUrlModalCmp;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.OpenUrlModalCmp(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_OpenUrlModalCmp_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_OpenUrlModalCmp_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.OpenUrlModalCmp>;
  _OpenUrlModalCmp_0_3:Wrapper_OpenUrlModalCmp;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_OpenUrlModalCmp_Host0,renderType_OpenUrlModalCmp_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_OpenUrlModalCmp0(this.viewUtils,this,0,this._el_0);
    this._OpenUrlModalCmp_0_3 = new Wrapper_OpenUrlModalCmp(this.injectorGet(import8.NavParams,this.parentIndex),this.injectorGet(import9.ViewController,this.parentIndex),this.injectorGet(import10.DomSanitizer,this.parentIndex));
    this.compView_0.create(this._OpenUrlModalCmp_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._OpenUrlModalCmp_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.OpenUrlModalCmp) && (0 === requestNodeIndex))) { return this._OpenUrlModalCmp_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._OpenUrlModalCmp_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const OpenUrlModalCmpNgFactory:import7.ComponentFactory<import0.OpenUrlModalCmp> = new import7.ComponentFactory<import0.OpenUrlModalCmp>('ng-component',View_OpenUrlModalCmp_Host0,import0.OpenUrlModalCmp);
const styles_OpenUrlModalCmp:any[] = ([] as any[]);
var renderType_OpenUrlModalCmp:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_OpenUrlModalCmp,{});
export class View_OpenUrlModalCmp0 extends import1.AppView<import0.OpenUrlModalCmp> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import11.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  compView_3:import1.AppView<import12.Navbar>;
  _Navbar_3_3:import13.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  _ToolbarItem_5_3:import14.Wrapper_ToolbarItem;
  _query_Button_5_0:import15.QueryList<any>;
  _text_6:any;
  _el_7:any;
  compView_7:import1.AppView<import16.Button>;
  _Button_7_3:import17.Wrapper_Button;
  _text_8:any;
  _el_9:any;
  _Icon_9_3:import18.Wrapper_Icon;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  compView_13:import1.AppView<import19.ToolbarTitle>;
  _ToolbarTitle_13_3:import20.Wrapper_ToolbarTitle;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  compView_18:import1.AppView<import21.Content>;
  _Content_18_3:import22.Wrapper_Content;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_OpenUrlModalCmp0,renderType_OpenUrlModalCmp,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_35 = import6.UNINITIALIZED;
    this._expr_36 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'ion-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._Header_1_3 = new import11.Wrapper_Header(this.parentView.injectorGet(import23.Config,this.parentIndex),new import24.ElementRef(this._el_1),this.renderer,this.parentView.injectorGet(import9.ViewController,this.parentIndex,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'ion-navbar',new import3.InlineArray2(2,'class','toolbar'),(null as any));
    this.compView_3 = new import13.View_Navbar0(this.viewUtils,this,3,this._el_3);
    this._Navbar_3_3 = new import13.Wrapper_Navbar(this.parentView.injectorGet(import25.App,this.parentIndex),this.parentView.injectorGet(import9.ViewController,this.parentIndex,(null as any)),this.parentView.injectorGet(import26.NavController,this.parentIndex,(null as any)),this.parentView.injectorGet(import23.Config,this.parentIndex),new import24.ElementRef(this._el_3),this.renderer);
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,(null as any),'ion-buttons',new import3.InlineArray2(2,'end',''),(null as any));
    this._ToolbarItem_5_3 = new import14.Wrapper_ToolbarItem(this.parentView.injectorGet(import23.Config,this.parentIndex),new import24.ElementRef(this._el_5),this.renderer,this.parentView.injectorGet(import27.Toolbar,this.parentIndex,(null as any)),this._Navbar_3_3.context);
    this._query_Button_5_0 = new import15.QueryList<any>();
    this._text_6 = this.renderer.createText(this._el_5,'\n          ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'button',new import3.InlineArray4(4,'icon-only','','ion-button',''),(null as any));
    this.compView_7 = new import17.View_Button0(this.viewUtils,this,7,this._el_7);
    this._Button_7_3 = new import17.Wrapper_Button('',this.parentView.injectorGet(import23.Config,this.parentIndex),new import24.ElementRef(this._el_7),this.renderer);
    this._text_8 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,(null as any),'ion-icon',new import3.InlineArray4(4,'name','close','role','img'),(null as any));
    this._Icon_9_3 = new import18.Wrapper_Icon(this.parentView.injectorGet(import23.Config,this.parentIndex),new import24.ElementRef(this._el_9),this.renderer);
    this._text_10 = this.renderer.createText((null as any),'\n          ',(null as any));
    this.compView_7.create(this._Button_7_3.context);
    this._text_11 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,(null as any),'ion-title',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_13 = new import20.View_ToolbarTitle0(this.viewUtils,this,13,this._el_13);
    this._ToolbarTitle_13_3 = new import20.Wrapper_ToolbarTitle(this.parentView.injectorGet(import23.Config,this.parentIndex),new import24.ElementRef(this._el_13),this.renderer,this.parentView.injectorGet(import27.Toolbar,this.parentIndex,(null as any)),this._Navbar_3_3.context);
    this._text_14 = this.renderer.createText((null as any),'',(null as any));
    this.compView_13.create(this._ToolbarTitle_13_3.context);
    this._text_15 = this.renderer.createText((null as any),'\n      ',(null as any));
    this.compView_3.create(this._Navbar_3_3.context);
    this._text_16 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_17 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,parentRenderNode,'ion-content',new import3.InlineArray2(2,'class','open-url-modal-content'),(null as any));
    this.compView_18 = new import22.View_Content0(this.viewUtils,this,18,this._el_18);
    this._Content_18_3 = new import22.Wrapper_Content(this.parentView.injectorGet(import23.Config,this.parentIndex),this.parentView.injectorGet(import28.Platform,this.parentIndex),this.parentView.injectorGet(import29.DomController,this.parentIndex),new import24.ElementRef(this._el_18),this.renderer,this.parentView.injectorGet(import25.App,this.parentIndex),this.parentView.injectorGet(import30.Keyboard,this.parentIndex),this.parentView.injectorGet(import31.NgZone,this.parentIndex),this.parentView.injectorGet(import9.ViewController,this.parentIndex,(null as any)),this.parentView.injectorGet(import32.Tabs,this.parentIndex,(null as any)));
    this._text_19 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,(null as any),'iframe',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_18.create(this._Content_18_3.context);
    this._text_22 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_7));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.Icon) && (9 === requestNodeIndex))) { return this._Icon_9_3.context; }
    if (((token === import16.Button) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Button_7_3.context; }
    if (((token === import34.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarItem_5_3.context; }
    if (((token === import19.ToolbarTitle) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ToolbarTitle_13_3.context; }
    if (((token === import12.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Navbar_3_3.context; }
    if (((token === import27.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Header_1_3.context; }
    if (((token === import21.Content) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Content_18_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.ngDoCheck(this,this._el_1,throwOnChange);
    const currVal_3_0_0:any = this.context.options.color;
    this._Navbar_3_3.check_color(currVal_3_0_0,throwOnChange,false);
    this._Navbar_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    this._ToolbarItem_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    if (this._Button_7_3.ngDoCheck(this,this._el_7,throwOnChange)) { this.compView_7.markAsCheckOnce(); }
    const currVal_9_0_0:any = 'close';
    this._Icon_9_3.check_name(currVal_9_0_0,throwOnChange,false);
    this._Icon_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    if (this._ToolbarTitle_13_3.ngDoCheck(this,this._el_13,throwOnChange)) { this.compView_13.markAsCheckOnce(); }
    if (this._Content_18_3.ngDoCheck(this,this._el_18,throwOnChange)) { this.compView_18.markAsCheckOnce(); }
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_7_3.context]);
        this._ToolbarItem_5_3.context._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_7_3.context.ngAfterContentInit(); }
    }
    this._Navbar_3_3.checkHost(this,this.compView_3,this._el_3,throwOnChange);
    this._Icon_9_3.checkHost(this,this,this._el_9,throwOnChange);
    const currVal_35:any = import3.inlineInterpolate(1,'',this.context.options.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setText(this._text_14,currVal_35);
      this._expr_35 = currVal_35;
    }
    this._Content_18_3.checkHost(this,this.compView_18,this._el_18,throwOnChange);
    const currVal_36:any = this.context.safeUrl;
    if (import3.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementProperty(this._el_20,'src',this.viewUtils.sanitizer.sanitize(import35.SecurityContext.RESOURCE_URL,currVal_36));
      this._expr_36 = currVal_36;
    }
    this.compView_3.detectChanges(throwOnChange);
    this.compView_7.detectChanges(throwOnChange);
    this.compView_13.detectChanges(throwOnChange);
    this.compView_18.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_3.destroy();
    this.compView_7.destroy();
    this.compView_13.destroy();
    this.compView_18.destroy();
    this._Icon_9_3.ngOnDestroy();
    this._Content_18_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 3) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 3) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 3) && (ngContentIndex == 2))) { cb(this._el_5,ctx); }
    if (((nodeIndex == 3) && (ngContentIndex == 3))) {
      cb(this._text_4,ctx);
      cb(this._text_12,ctx);
      cb(this._el_13,ctx);
      cb(this._text_15,ctx);
    }
    if (((nodeIndex == 7) && (ngContentIndex == 0))) {
      cb(this._text_8,ctx);
      cb(this._el_9,ctx);
      cb(this._text_10,ctx);
    }
    if (((nodeIndex == 13) && (ngContentIndex == 0))) { cb(this._text_14,ctx); }
    if (((nodeIndex == 18) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 1))) {
      cb(this._text_19,ctx);
      cb(this._el_20,ctx);
      cb(this._text_21,ctx);
    }
    if (((nodeIndex == 18) && (ngContentIndex == 2))) {  }
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.dismiss()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}