import { Renderer2, ElementRef, EventEmitter, AfterViewInit, OnDestroy } from '@angular/core';
import { Platform } from 'ionic-angular';
import { SuperTabsConfig } from '../super-tabs/super-tabs';
export declare class SuperTabsContainer implements AfterViewInit, OnDestroy {
    private el;
    private rnd;
    private plt;
    config: SuperTabsConfig;
    tabsCount: number;
    selectedTabIndex: number;
    tabSelect: EventEmitter<number>;
    tabWillChange: EventEmitter<any>;
    tabDidChange: EventEmitter<any>;
    onDrag: EventEmitter<TouchEvent>;
    containerPosition: number;
    container: ElementRef;
    tabWidth: number;
    containerWidth: number;
    leftThreshold: number;
    rightThreshold: number;
    private minPosX;
    private maxPosX;
    private gesture;
    private globalSwipeEnabled;
    private swipeEnabledPerTab;
    constructor(el: ElementRef, rnd: Renderer2, plt: Platform);
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    enableTabsSwipe(enable: boolean): void;
    enableTabSwipe(tabIndex: number, enable: boolean): void;
    refreshDimensions(): void;
    getNativeElement(): HTMLElement;
    private init();
    private setSelectedTab(index);
    private calculateContainerWidth();
    setHeight(height: number): void;
    private setContainerWidth();
    slideTo(index: number): void;
    private moveContainer(animate?, positionX?);
    private refreshMinMax();
}
